name: Deploy POD4 Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}  # Correct token env var for Terraform Cloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Get EC2 Public IP from Terraform Output
        id: get_ip
        run: |
          echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Wait for EC2 to be ready
        run: sleep 60

      - name: Deploy POD4 Website to EC2
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem

          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./POD4/ ubuntu@$INSTANCE_IP:/tmp/pod4/

          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$INSTANCE_IP << 'EOF'
            if ! command -v nginx > /dev/null; then
              sudo apt update
              sudo apt install -y nginx
            fi
            sudo rm -rf /var/www/html/*
            sudo mv /tmp/pod4/* /var/www/html/
            sudo systemctl restart nginx
          EOF
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
